# Generated by Django 4.1.1 on 2022-09-24 06:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_pokemon_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='updated',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
    ]
